#include "icp.h"
	SUBROUTINE CURSOR_ON(DISPID)
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++C
C	Dummy routine which interfaces with DEC SMG$SET_CURSOR_MODE	      C
C                                                                             C
C	Gayle Greene, March , 1995                                            C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++C
C
	IMPLICIT NONE

C  Calling parameters
	INTEGER*4	DISPID !DISPLAY ID

	RETURN
	END
