#include "icp.h"
	SUBROUTINE SCROLL_DISPLAY(DISPID)
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++C
C	Dummy routine which interfaces with DEC SMG$SCROLL_DISPLAY_AREA       C
C                                                                             C
C	Gayle Greene, March , 1995                                            C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++C
C
	IMPLICIT NONE

C  Calling parameters
	INTEGER*4	DISPID !DISPLAY ID

	print *,''
	RETURN
	END
